version: "3.5"
services:
  redis:
    image: redis:latest
  db:
    image: postgres:10.1-alpine
  web:
    build: .
    ports:
      - "3000:3000"
      - "5005:5005"
    env_file: .env
    volumes:
      - .:/api
    depends_on:
      - redis
      - db
    command:
      [
        "./wait-for-it.sh",
        "redis:6379",
        "-t",
        "120",
        "--",
        "./wait-for-it.sh",
        "db:5432",
        "-t",
        "120",
        "--",
        "./start.sh",
      ]
