# Generated by Django 2.1.5 on 2019-02-01 20:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('points', models.IntegerField(verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Consumption',
                'verbose_name_plural': 'Consumptions',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('point_expired_date', models.DateTimeField(verbose_name='Point Exipred Date')),
                ('used_points', models.IntegerField(verbose_name='Used Points')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Customer Tier',
                'verbose_name_plural': 'Customers Tier',
            },
        ),
        migrations.CreateModel(
            name='CustomerTierUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Customer', verbose_name='Customer')),
                ('customer_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.CustomerTier', verbose_name='Customer Tier')),
            ],
            options={
                'verbose_name': 'Customer Tier Used',
                'verbose_name_plural': 'Customers Tier Used',
            },
        ),
        migrations.CreateModel(
            name='Expired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Expired',
                'verbose_name_plural': 'Expireds',
            },
        ),
        migrations.CreateModel(
            name='IndustrialRepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Industrial Repass',
                'verbose_name_plural': 'Industrial Repasses',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industrys',
            },
        ),
        migrations.CreateModel(
            name='PointsReversal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('points', models.IntegerField(verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Point Reversal',
                'verbose_name_plural': 'Points Reversal',
            },
        ),
        migrations.CreateModel(
            name='PromotionRepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('promotion', models.IntegerField(verbose_name='Promotion')),
                ('points', models.IntegerField(verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Pomotion Repass',
                'verbose_name_plural': 'Pomotion Repasses',
            },
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('used_points', models.IntegerField(verbose_name='Used Points')),
                ('days_before_expiration', models.IntegerField(help_text='Total de dias que vai expirar quando o usuário ganhar os pontos', verbose_name='Days Before Expiration')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('point_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Point Value')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Contract', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Tier',
                'verbose_name_plural': 'Tiers',
            },
        ),
        migrations.CreateModel(
            name='TierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tier Type',
                'verbose_name_plural': 'Tier Types',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Identify')),
                ('track_type', models.IntegerField(choices=[(1, 'Resgate'), (2, 'Transferencia'), (3, 'Estorno'), (4, 'Repasse Indústria'), (5, 'Promoções'), (6, 'Expirado')], verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('customer_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransferDestination', to='olympus.Customer', verbose_name='Customer Destination')),
                ('customer_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TransferOrigen', to='olympus.Customer', verbose_name='Customer Origen')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Track', verbose_name='Track')),
            ],
            options={
                'verbose_name': 'Expired',
                'verbose_name_plural': 'Expireds',
            },
        ),
        migrations.AddField(
            model_name='tier',
            name='tier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.TierType', verbose_name='Tier Type'),
        ),
        migrations.AddField(
            model_name='promotionrepass',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='pointsreversal',
            name='reversed_tracking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReversedTracking', to='olympus.Track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='pointsreversal',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Track', to='olympus.Track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='industrialrepass',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Industry', verbose_name='Indústria'),
        ),
        migrations.AddField(
            model_name='industrialrepass',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='expired',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='customertierused',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='customertier',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Tier', verbose_name='Tier'),
        ),
        migrations.AddField(
            model_name='customertier',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Track', verbose_name='Track'),
        ),
        migrations.AddField(
            model_name='contract',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Industry', verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='consumption',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.Track', verbose_name='Track'),
        ),
    ]
